# Performance Analytics

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from sqlalchemy import create_engine
from scipy.stats import linregress

In [ ]:
engine = create_engine("sqlite:///../data/bluestock_mf.db")

In [ ]:
from sqlalchemy import create_engine

engine = create_engine("sqlite:///../mutual_fund.db")

In [ ]:
nav = pd.read_sql("SELECT * FROM nav_history", engine)

performance = pd.read_sql("SELECT * FROM scheme_performance", engine)

# Daily Return Calculation

In [ ]:
nav.info()

In [ ]:
nav["date"] = pd.to_datetime(nav["date"])

In [ ]:
nav.dtypes

In [ ]:
nav = nav.sort_values(["amfi_code", "date"])

In [ ]:
nav["daily_return"] = (
    nav.groupby("amfi_code")["nav"]
       .pct_change()
)

In [ ]:
nav.head(10)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,5))

sns.histplot(nav["daily_return"].dropna(), bins=100, kde=True)

plt.title("Distribution of Daily Returns")
plt.xlabel("Daily Return")
plt.ylabel("Frequency")

plt.show()

In [ ]:
cagr_df = performance[[
    "scheme_name",
    "return_1yr_pct",
    "return_3yr_pct",
    "return_5yr_pct"
]]

cagr_df.head()

In [ ]:
cagr_df = cagr_df.sort_values(
    by="return_3yr_pct",
    ascending=False
)

cagr_df.head(10)

In [ ]:
cagr_df.to_csv("cagr_comparison.csv", index=False)

In [ ]:
sharpe_df = performance[[
    "scheme_name",
    "sharpe_ratio"
]]

sharpe_df.head()

In [ ]:
sharpe_df = sharpe_df.sort_values(
    by="sharpe_ratio",
    ascending=False
)

sharpe_df.head(10)

In [ ]:
sharpe_df.to_csv("sharpe_ranking.csv", index=False)

In [ ]:
sortino_df = performance[[
    "scheme_name",
    "sortino_ratio"
]]

sortino_df.head()

In [ ]:
sortino_df = sortino_df.sort_values(
    by="sortino_ratio",
    ascending=False
)

sortino_df.head(10)

In [ ]:
sortino_df.to_csv("sortino_ranking.csv", index=False)

In [ ]:
alpha_beta_df = performance[[
    "scheme_name",
    "alpha",
    "beta"
]]

alpha_beta_df.head()

In [ ]:
alpha_beta_df = alpha_beta_df.sort_values(
    by="alpha",
    ascending=False
)

alpha_beta_df.head(10)

In [ ]:
alpha_beta_df.to_csv("alpha_beta.csv", index=False)

In [ ]:
drawdown_df = performance[[
    "scheme_name",
    "max_drawdown_pct"
]]

drawdown_df.head()

In [ ]:
drawdown_df = drawdown_df.sort_values(
    by="max_drawdown_pct",
    ascending=False
)

drawdown_df.head(10)

In [ ]:
drawdown_df.to_csv("drawdown_ranking.csv", index=False)

In [ ]:
score = performance[[
    "scheme_name",
    "return_3yr_pct",
    "sharpe_ratio",
    "alpha",
    "expense_ratio_pct",
    "max_drawdown_pct"
]].copy()

In [ ]:
score["ReturnRank"] = score["return_3yr_pct"].rank(ascending=False)

score["SharpeRank"] = score["sharpe_ratio"].rank(ascending=False)

score["AlphaRank"] = score["alpha"].rank(ascending=False)

score["ExpenseRank"] = score["expense_ratio_pct"].rank(ascending=True)

score["DrawdownRank"] = score["max_drawdown_pct"].rank(ascending=False)

In [ ]:
score["Score"] = (
    score["ReturnRank"] * 0.30 +
    score["SharpeRank"] * 0.25 +
    score["AlphaRank"] * 0.20 +
    score["ExpenseRank"] * 0.15 +
    score["DrawdownRank"] * 0.10
)

In [ ]:
score = score.sort_values("Score")

score.head(10)

In [ ]:
score.to_csv("fund_scorecard.csv", index=False)

In [ ]:
top5 = score.head(5)

top5

In [ ]:
benchmark = pd.read_csv("../data/10_benchmark_indices.csv")

In [ ]:
print(os.getcwd())

In [ ]:
os.listdir("..")

In [ ]:
benchmark.head()

In [ ]:
benchmark.info()

In [ ]:
benchmark["date"] = pd.to_datetime(benchmark["date"])

In [ ]:
benchmark = benchmark[
    benchmark["index_name"].isin(["NIFTY50", "NIFTY100"])
]

In [ ]:
import plotly.express as px

fig = px.line(
    benchmark,
    x="date",
    y="close_value",
    color="index_name",
    title="NIFTY 50 vs NIFTY 100"
)

fig.show()

In [ ]:
fig.write_html("benchmark_comparison.html")

In [ ]:
import sys
print(sys.executable)

In [ ]:
%pip install kaleido

In [1]:
import kaleido
print(kaleido.__version__)

AttributeError: module 'kaleido' has no attribute '__version__'

In [2]:
import plotly
print(plotly.__version__)

6.8.0

In [3]:
import sys
print(sys.executable)

c:\Users\acer\mutual_fund_analysis\venv\Scripts\python.exe

In [6]:
import pandas as pd
import plotly.express as px
from sqlalchemy import create_engine

In [7]:
engine = create_engine("sqlite:///../mutual_fund.db")

In [8]:
nav = pd.read_sql("SELECT * FROM nav_history", engine)

performance = pd.read_sql("SELECT * FROM scheme_performance", engine)

In [9]:
benchmark = pd.read_csv("../data/10_benchmark_indices.csv")

benchmark["date"] = pd.to_datetime(benchmark["date"])

benchmark = benchmark[
    benchmark["index_name"].isin(["NIFTY50", "NIFTY100"])
]

In [10]:
fig = px.line(
    benchmark,
    x="date",
    y="close_value",
    color="index_name",
    title="NIFTY 50 vs NIFTY 100"
)

fig.show()

In [11]:
fig.write_html("benchmark_comparison.html")

# Top 5 Mutual Funds

In [13]:
score = performance[[
    "scheme_name",
    "return_3yr_pct",
    "sharpe_ratio",
    "alpha",
    "expense_ratio_pct",
    "max_drawdown_pct"
]].copy()

In [14]:
score["ReturnRank"] = score["return_3yr_pct"].rank(ascending=False)

score["SharpeRank"] = score["sharpe_ratio"].rank(ascending=False)

score["AlphaRank"] = score["alpha"].rank(ascending=False)

score["ExpenseRank"] = score["expense_ratio_pct"].rank(ascending=True)

score["DrawdownRank"] = score["max_drawdown_pct"].rank(ascending=False)

In [15]:
score["Score"] = (
    score["ReturnRank"] * 0.30 +
    score["SharpeRank"] * 0.25 +
    score["AlphaRank"] * 0.20 +
    score["ExpenseRank"] * 0.15 +
    score["DrawdownRank"] * 0.10
)

In [16]:
score = score.sort_values("Score")

In [17]:
top5 = score.head(5)

top5[["scheme_name", "Score"]]

                                      scheme_name  Score
22         Kotak Flexicap Fund - Regular - Growth  12.30
2      SBI Small Cap Fund - Regular Plan - Growth  12.75
14       ICICI Pru Liquid Fund - Regular - Growth  12.80
9    HDFC Short Term Debt Fund - Regular - Growth  12.90
21  Kotak Emerging Equity Fund - Regular - Growth  13.70

In [18]:
top5 = score.head(5)

top5_codes = performance[
    performance["scheme_name"].isin(top5["scheme_name"])
][["amfi_code", "scheme_name"]]

top5_codes

    amfi_code                                    scheme_name
2      119598     SBI Small Cap Fund - Regular Plan - Growth
9      100025   HDFC Short Term Debt Fund - Regular - Growth
14     120507       ICICI Pru Liquid Fund - Regular - Growth
21     120842  Kotak Emerging Equity Fund - Regular - Growth
22     120843         Kotak Flexicap Fund - Regular - Growth

In [19]:
top5_nav = nav[
    nav["amfi_code"].isin(top5_codes["amfi_code"])
]

top5_nav.head()

      amfi_code        date      nav
1150     100025  2022-01-03  26.3169
1151     100025  2022-01-04  26.2234
1152     100025  2022-01-05  26.2221
1153     100025  2022-01-06  26.1728
1154     100025  2022-01-07  26.2261

In [20]:
top5_nav = top5_nav.merge(
    top5_codes,
    on="amfi_code"
)

top5_nav.head()

,amfi_code,date,nav,scheme_name
0,100025,2022-01-03,26.3169,HDFC Short Term Debt Fund - Regular - Growth
1,100025,2022-01-04,26.2234,HDFC Short Term Debt Fund - Regular - Growth
2,100025,2022-01-05,26.2221,HDFC Short Term Debt Fund - Regular - Growth
3,100025,2022-01-06,26.1728,HDFC Short Term Debt Fund - Regular - Growth
4,100025,2022-01-07,26.2261,HDFC Short Term Debt Fund - Regular - Growth

In [21]:
top5_nav["rebased_nav"] = top5_nav.groupby("scheme_name")["nav"].transform(
    lambda x: x / x.iloc[0] * 100
)

In [22]:
import plotly.express as px

fig = px.line(
    top5_nav,
    x="date",
    y="rebased_nav",
    color="scheme_name",
    title="Top 5 Mutual Funds Performance"
)

fig.show()

In [23]:
benchmark["rebased_value"] = benchmark.groupby("index_name")["close_value"].transform(
    lambda x: x / x.iloc[0] * 100
)

In [24]:
benchmark_plot = benchmark.rename(
    columns={
        "index_name": "scheme_name",
        "rebased_value": "rebased_nav"
    }
)

In [25]:
benchmark_plot = benchmark_plot[
    ["date", "scheme_name", "rebased_nav"]
]

In [26]:
fund_plot = top5_nav[
    ["date", "scheme_name", "rebased_nav"]
]

In [27]:
comparison = pd.concat(
    [fund_plot, benchmark_plot],
    ignore_index=True
)

In [28]:
import plotly.express as px

fig = px.line(
    comparison,
    x="date",
    y="rebased_nav",
    color="scheme_name",
    title="Top 5 Mutual Funds vs NIFTY50 & NIFTY100"
)

fig.show()

In [29]:
fig.write_html("benchmark_comparison.html")

In [31]:
alpha_beta_df = performance[[
    "scheme_name",
    "alpha",
    "beta"
]]

alpha_beta_df = alpha_beta_df.sort_values(
    by="alpha",
    ascending=False
)

In [32]:
alpha_beta_df.to_csv("alpha_beta.csv", index=False)

In [33]:
score.to_csv("fund_scorecard.csv", index=False)

alpha_beta_df.to_csv("alpha_beta.csv", index=False)

In [34]:
fig.write_html("benchmark_comparison.html")